#ifndef _CMAKEVARS_HPP_
#define _CMAKEVARS_HPP_

#define PROJECT_VERSION_MAJOR 0
#define PROJECT_VERSION_MINOR 2
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION_TWEAK 0
#define DEBUG 0

#endif //_CMAKEVARS_HPP_
